import { Colors } from "constants/Colors";
import { FILL_WIDGET_MIN_WIDTH } from "constants/minWidthConstants";
import { ResponsiveBehavior } from "utils/autoLayout/constants";
import type { WidgetProps } from "widgets/BaseWidget";
import {
  ButtonTypes,
  ColumnTypes,
  TableInlineEditTypes,
  BUTTON_DEFAULT_CONFIG,
} from "./constants";
import type { TableWidgetProps } from "./constants";
import IconSVG from "./icon.svg";
import Widget from "./widget";
import type {
  WidgetQueryConfig,
  WidgetQueryGenerationFormConfig,
} from "WidgetQueryGenerators/types";
import type { PropertyUpdates, SnipingModeProperty } from "widgets/constants";
import { WIDGET_TAGS } from "constants/WidgetConstants";
import {
  ButtonVariantTypes,
  CheckboxGroupAlignmentTypes,
} from "components/constants";
import { theme } from "antd";

import { JSONFormDefaults } from "./widget/propertyConfig/JSONForm";
export const CONFIG = {
  type: Widget.getWidgetType(),
  name: "antd 表格",
  searchTags: ["datagrid", "table"],
  iconSVG: IconSVG,
  isCanvas: true,
  tags: [WIDGET_TAGS.ANTD],
  needsMeta: true,
  needsHeightForContent: true,

  defaults: {
    defaultFormData: {},
    sourceData: {},
    autoGenerateTableForm: true,
    autoFormConfig: {
      label: "表单配置",
      id: "config",
      config: {
        ...JSONFormDefaults,
        jsonFormPopType: "modal",
        disabledWhenInvalid: false,
        title: "新建",
        editTitle: "编辑",
        borderWidth: "0",
        showReset: false,
        showCancel: true,
        fixMessageHeight: 200,
        buttonAlignment: CheckboxGroupAlignmentTypes.END,
        id: "config",
        label: "表单配置",
        modalWidth: 520,
        modalHeight: 520,
      },
    },
    tablePrimaryColor: theme.defaultSeed.colorPrimary,
    tableType: "normal",
    addNewRowText: "新增一行",
    allowAddNewRow: false,
    addNewRowPosition: "bottom",
    editableKeys: [],
    editType: "multiple",
    rightColumn: 64,
    rows: 48,
    columns: 64,
    width: 456,
    toolBarActions: {
      create: {
        ...BUTTON_DEFAULT_CONFIG,
        buttonVariant: ButtonVariantTypes.PRIMARY,
        buttonSize: undefined,
        menuButtonLabel: "新建",
        label: "新建",
        id: "create",
        widgetId: "",
        index: 0,
        tooltip: "",
        buttonLabel: "新建",
        btnIconName: "ant-design:PlusOutlined",
        onBtnClick: "",
        isHideDelete: true,
        iconName: "ant-design:PlusOutlined",
      },
      addNewRow: {
        ...BUTTON_DEFAULT_CONFIG,
        buttonVariant: ButtonVariantTypes.PRIMARY,
        buttonSize: undefined,
        menuButtonLabel: "新增一行",
        label: "新增一行",
        id: "addNewRow",
        widgetId: "",
        index: 1,
        tooltip: "",
        buttonLabel: "新增一行",
        btnIconName: "ant-design:PlusOutlined",
        onBtnClick: "",
        isHideDelete: true,
        iconName: "ant-design:PlusOutlined",
        isHiddenItem: true,
      },
      saveDataSource: {
        ...BUTTON_DEFAULT_CONFIG,
        buttonVariant: ButtonVariantTypes.PRIMARY,
        buttonSize: undefined,
        menuButtonLabel: "保存数据",
        label: "保存数据",
        id: "saveDataSource",
        widgetId: "",
        index: 2,
        tooltip: "",
        buttonLabel: "保存数据",
        btnIconName: "ant-design:SaveOutlined",
        onBtnClick: "{{showAlert('请先配置保存数据按钮的动作', 'warning');}}",
        isHideDelete: true,
        isHiddenItem: true,
      },
    },
    rowSelectionActions: {
      // 批量删除
      delete: {
        ...BUTTON_DEFAULT_CONFIG,
        menuButtonLabel: "批量删除",
        label: "批量删除",
        id: "delete",
        widgetId: "",
        index: 0,
        tooltip: "批量删除",
        buttonLabel: "批量删除",
        btnIconName: "ant-design:DeleteOutlined",
        onBtnClick: "{{showAlert('请先配置批量删除按钮的动作', 'warning');}}",
      },
      // 导出数据
      export: {
        ...BUTTON_DEFAULT_CONFIG,
        menuButtonLabel: "导出数据",
        label: "导出数据",
        id: "export",
        widgetId: "",
        index: 1,
        tooltip: "导出数据",
        buttonLabel: "导出数据",
        btnIconName: "ant-design:DownloadOutlined",
        onBtnClick: "{{showAlert('请先配置导出数据按钮的动作', 'warning');}}",
      },
    },
    editingActions: {
      save: {
        ...BUTTON_DEFAULT_CONFIG,
        menuButtonLabel: "保存",
        label: "保存",
        id: "save",
        widgetId: "",
        index: 0,
        tooltip: "保存",
        buttonLabel: "保存",
        btnIconName: "ant-design:SaveOutlined",
        onBtnClick: "",
        isHideDelete: true,
      },
      delete: {
        ...BUTTON_DEFAULT_CONFIG,

        label: "删除",
        id: "delete",
        widgetId: "",
        index: 1,
        tooltip: "删除",
        buttonLabel: "删除",
        btnIconName: "ant-design:DeleteOutlined",
        onBtnClick: "",
        isHideDelete: true,
      },
      cancel: {
        ...BUTTON_DEFAULT_CONFIG,
        label: "取消",
        id: "cancel",
        widgetId: "",
        index: 1,
        tooltip: "取消",
        buttonLabel: "取消",
        btnIconName: "ant-design:CloseOutlined",
        onBtnClick: "",
        isHideDelete: true,
      },
    },
    columnActions: {
      details: {
        ...BUTTON_DEFAULT_CONFIG,
        menuButtonLabel: "查看",
        isHideDelete: true,
        label: "查看",
        id: "details",
        widgetId: "",
        index: 0,
        tooltip: "查看",
        buttonLabel: "查看",
        btnIconName: "ant-design:EyeOutlined",
        onBtnClick: "{{showAlert('请先配置查看按钮的动作', 'warning');}}",
      },
      edit: {
        ...BUTTON_DEFAULT_CONFIG,
        menuButtonLabel: "编辑",
        isHideDelete: true,
        label: "编辑",
        id: "edit",
        widgetId: "",
        index: 0,
        tooltip: "编辑",
        buttonLabel: "编辑",
        btnIconName: "ant-design:EditOutlined",
        onBtnClick: "{{showAlert('请先配置编辑按钮的动作', 'warning');}}",
      },
      delete: {
        ...BUTTON_DEFAULT_CONFIG,
        menuButtonLabel: "删除",
        label: "删除",
        id: "delete",
        widgetId: "",
        index: 1,
        tooltip: "删除",
        buttonLabel: "删除",
        btnIconName: "ant-design:DeleteOutlined",
        onBtnClick: "{{showAlert('请先配置删除按钮的动作', 'warning');}}",
      },
    },
    showSizeChanger: true,
    defaultPageSize: 10,
    paginationDisabled: false,
    simplePagination: false,
    hideOnSinglePage: false,
    paginationSize: "default",
    showQuickJumper: true,
    headerBorderRadius: 0,
    // borderRadius: 0,
    isVisibleSearchForm: true,
    actionWidth: 130,
    responsiveBehavior: ResponsiveBehavior.Fill,
    minWidth: FILL_WIDGET_MIN_WIDTH,
    canFreezeColumn: true,
    animateLoading: true,
    isVisibleDensity: true,
    isVisibleCellSetting: true,
    isVisibleRefresh: true,
    columnUpdatedAt: Date.now(),
    defaultSelectedRowIndex: undefined,
    defaultSelectedRowKeys: [],
    label: "数据",
    widgetName: "ProTable",
    searchKey: "",
    textSize: "0.875rem",
    horizontalAlignment: "LEFT",
    verticalAlignment: "CENTER",
    totalRecordsCount: 0,
    dynamicPropertyPathList: [],
    borderColor: Colors.GREY_5,
    borderWidth: "1",
    dynamicBindingPathList: [],
    primaryColumns: {},
    tableData: "",
    childrenColumnName: "children",
    columnWidthMap: {},
    columnOrder: [],
    // enableClientSideSearch: true,
    multiRowSelection: false,
    isVisibleSearch: true,
    isVisibleDownload: true,
    isVisiblePagination: true,
    serverSidePaginationEnabled: true,
    allowRowSelection: false,
    rowSelectionType: "checkbox",
    isRemoteSort: false,
    delimiter: ",",
    version: 2,
    tableInlineEditType: TableInlineEditTypes.CUSTOM,
  },
  properties: {
    derived: Widget.getDerivedPropertiesMap(),
    default: Widget.getDefaultPropertiesMap(),
    meta: Widget.getMetaPropertiesMap(),
    contentConfig: Widget.getPropertyPaneContentConfig(),
    styleConfig: Widget.getPropertyPaneStyleConfig(),
    stylesheetConfig: Widget.getStylesheetConfig(),
    loadingProperties: Widget.getLoadingProperties(),
    autocompleteDefinitions: Widget.getAutocompleteDefinitions(),
    setterConfig: Widget.getSetterConfig(),
  },
  methods: {
    getQueryGenerationConfig: (widgetProps: WidgetProps) => {
      return Widget.getQueryGenerationConfig(widgetProps);
    },
    getPropertyUpdatesForQueryBinding: (
      queryConfig: WidgetQueryConfig,
      widget: WidgetProps,
      formConfig: WidgetQueryGenerationFormConfig,
    ) => {
      return Widget.getPropertyUpdatesForQueryBinding(
        queryConfig,
        widget as TableWidgetProps,
        formConfig,
      );
    },
    getSnipingModeUpdates: (
      propValueMap: SnipingModeProperty,
    ): PropertyUpdates[] => {
      return [
        {
          propertyPath: "tableData",
          propertyValue: propValueMap.data,
          isDynamicPropertyPath: false,
        },
      ];
    },
  },
  autoLayout: {
    widgetSize: [
      {
        viewportMinWidth: 0,
        configuration: () => {
          return {
            minWidth: "100%",
            minHeight: "400px",
          };
        },
      },
    ],
  },
};

export default Widget;
