export const data = [
  {
    __originalIndex__: 0,
    __primaryKey__: "630000199501101896",
    id: "630000199501101896",
    status: false,
    name: "电群研共国部",
    code: "GCOB301",
    manager: "梁超",
    employeeCount: 116,
    description:
      "个整油照定家集信风质生率工圆毛华。极听置常联该么积论养确专声生。",
    phone: "19728776313",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "610000199403241138",
        name: "非院办市部",
        code: "UBQV266",
        manager: "黎霞",
        employeeCount: 39,
        description: "门省究子据家林容气程直知导查料具发。",
        children: [
          {
            id: "110000198007310426",
            name: "社即提四组",
            code: "FE657",
            manager: "毛秀兰",
            employeeCount: 8,
            description: "革术农其应区你情存证发争处率。",
            children: [],
            createdAt: "2024-09-25",
            __originalIndex__: 0,
            __originalIndexPath__: "0.0.0",
            __primaryKey__: "110000198007310426",
          },
          {
            id: "460000200007074101",
            name: "江步革组",
            code: "DJG153",
            manager: "崔静",
            employeeCount: 14,
            description:
              "京海头领才求法己家型压小再月口化由。千到单结运间农成造般会向为。",
            children: [],
            createdAt: "2024-09-26",
            __originalIndex__: 1,
            __originalIndexPath__: "0.0.1",
            __primaryKey__: "460000200007074101",
          },
        ],
        createdAt: "2024-09-24",
        __originalIndex__: 0,
        __originalIndexPath__: "0.0",
        __primaryKey__: "610000199403241138",
      },
      {
        id: "420000201802182846",
        name: "度眼特划部",
        code: "JOWX865",
        manager: "黎桂英",
        employeeCount: 44,
        description: "山世说便再社于眼眼维严面证后影面。",
        children: [
          {
            id: "530000201207279470",
            name: "半西建组",
            code: "TQU720",
            manager: "蔡明",
            employeeCount: 6,
            description:
              "于却列少当能对战使年采满而求须可带。线酸构林易联种由更速连定名。",
            children: [],
            createdAt: "2024-09-26",
            __originalIndex__: 0,
            __originalIndexPath__: "0.1.0",
            __primaryKey__: "530000201207279470",
          },
          {
            id: "420000201610276469",
            name: "道须油写组",
            code: "IMN377",
            manager: "高军",
            employeeCount: 14,
            description:
              "美所周科算边将标因般利才。果平些特族水养入度条联住团器快飞在或。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 1,
            __originalIndexPath__: "0.1.1",
            __primaryKey__: "420000201610276469",
          },
          {
            id: "210000202211096140",
            name: "性装组",
            code: "GOSW216",
            manager: "胡磊",
            employeeCount: 14,
            description: "自律文也据其气院许则例院单民规。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 2,
            __originalIndexPath__: "0.1.2",
            __primaryKey__: "210000202211096140",
          },
        ],
        createdAt: "2024-09-25",
        __originalIndex__: 1,
        __originalIndexPath__: "0.1",
        __primaryKey__: "420000201802182846",
      },
      {
        id: "530000200204144197",
        name: "时两表形备部",
        code: "TX569",
        manager: "侯平",
        employeeCount: 37,
        description:
          "住论直建近十阶长验白术战式正性都。民常门代第方什根受报十今号观族切。越一么算同四领二用商约养联反走走。",
        children: [
          {
            id: "450000202402248949",
            name: "员及红思组",
            code: "WYH378",
            manager: "丁军",
            employeeCount: 13,
            description: "料示提北率观第日列能才此收使运其关。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 0,
            __originalIndexPath__: "0.2.0",
            __primaryKey__: "450000202402248949",
          },
          {
            id: "11000019881004776X",
            name: "地干信组",
            code: "BQX481",
            manager: "何平",
            employeeCount: 6,
            description:
              "太公度干能工往省七八府流新难。意量个们党派却元红导等听料有。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 1,
            __originalIndexPath__: "0.2.1",
            __primaryKey__: "11000019881004776X",
          },
          {
            id: "710000197006083150",
            name: "立证组",
            code: "UBXK847",
            manager: "彭军",
            employeeCount: 14,
            description:
              "无给声实他把并那知无步而眼南。龙进类联计思极流片单这影那亲。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 2,
            __originalIndexPath__: "0.2.2",
            __primaryKey__: "710000197006083150",
          },
        ],
        createdAt: "2024-09-26",
        __originalIndex__: 2,
        __originalIndexPath__: "0.2",
        __primaryKey__: "530000200204144197",
      },
      {
        id: "230000198804034310",
        name: "被识思取部",
        code: "KXKD546",
        manager: "贺磊",
        employeeCount: 31,
        description:
          "拉多能物重研确点团即气电改低电定党。油拉战较结住温开而而分统专次思。",
        children: [
          {
            id: "530000200410305772",
            name: "象从多组",
            code: "HZB662",
            manager: "阎强",
            employeeCount: 11,
            description:
              "气会难红面日离当难些周张并比。为该际须油变并变转济育属什性更电并志。外向党布度争它部律意器用建。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 0,
            __originalIndexPath__: "0.3.0",
            __primaryKey__: "530000200410305772",
          },
        ],
        createdAt: "2024-09-27",
        __originalIndex__: 3,
        __originalIndexPath__: "0.3",
        __primaryKey__: "230000198804034310",
      },
    ],
    createdAt: "2024-09-23 00:00",
  },
  {
    __originalIndex__: 1,
    __primaryKey__: "430000201311103869",
    id: "430000201311103869",
    status: true,
    name: "军运原条部",
    code: "XPSV636",
    manager: "郑芳",
    employeeCount: 53,
    description: "条路并重调养用复究速层被。",
    phone: "17322202444",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "350000198801264628",
        name: "越准例部",
        code: "VSO560",
        manager: "范霞",
        employeeCount: 41,
        description:
          "规头把家我太现要处来来连面深个。圆正通又保习王问整精儿温任究改。",
        children: [
          {
            id: "45000020221008111X",
            name: "会南持样组",
            code: "RJHQ686",
            manager: "魏明",
            employeeCount: 10,
            description: "专号温将大地节县位情员我此取。",
            children: [],
            createdAt: "2024-09-26",
            __originalIndex__: 0,
            __originalIndexPath__: "1.0.0",
            __primaryKey__: "45000020221008111X",
          },
          {
            id: "610000202201175798",
            name: "很外做组",
            code: "JXP557",
            manager: "宋静",
            employeeCount: 8,
            description:
              "情队自别一期民划太定度心素。代内问学劳都运的然即复派且基党什。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 1,
            __originalIndexPath__: "1.0.1",
            __primaryKey__: "610000202201175798",
          },
        ],
        createdAt: "2024-09-25",
        __originalIndex__: 0,
        __originalIndexPath__: "1.0",
        __primaryKey__: "350000198801264628",
      },
      {
        id: "110000198009262739",
        name: "完通支线部",
        code: "JTC167",
        manager: "阎平",
        employeeCount: 30,
        description:
          "资光使领须精将观际生计省因日值厂精米。三物办青除格们形多本报织。",
        children: [
          {
            id: "61000020031127208X",
            name: "照极种组",
            code: "STOC166",
            manager: "张洋",
            employeeCount: 11,
            description:
              "社增眼度会把很受题难线干。元民权本人两子已法海已劳队至。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 0,
            __originalIndexPath__: "1.1.0",
            __primaryKey__: "61000020031127208X",
          },
          {
            id: "630000197012080466",
            name: "极边利通组",
            code: "GY851",
            manager: "熊芳",
            employeeCount: 11,
            description: "美工七七权知类识众共很任值体华身。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 1,
            __originalIndexPath__: "1.1.1",
            __primaryKey__: "630000197012080466",
          },
        ],
        createdAt: "2024-09-26",
        __originalIndex__: 1,
        __originalIndexPath__: "1.1",
        __primaryKey__: "110000198009262739",
      },
      {
        id: "640000197609282230",
        name: "头值关多别部",
        code: "QOH526",
        manager: "蒋桂英",
        employeeCount: 24,
        description:
          "科月算建圆百此专回个存完养次。来何合消又到中照被感没是引外集儿其。品技性商员再四何增厂解路。",
        children: [
          {
            id: "460000199001291265",
            name: "很务报来组",
            code: "KS341",
            manager: "方霞",
            employeeCount: 11,
            description:
              "住相资精务复十专提命么领油到半会。着起小张音基受期很选术式酸决第战。金我名记电长们六济精感议间队来万。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 0,
            __originalIndexPath__: "1.2.0",
            __primaryKey__: "460000199001291265",
          },
        ],
        createdAt: "2024-09-27",
        __originalIndex__: 2,
        __originalIndexPath__: "1.2",
        __primaryKey__: "640000197609282230",
      },
    ],
    createdAt: "2024-09-24 00:00",
  },
  {
    __originalIndex__: 2,
    __primaryKey__: "230000200104243285",
    id: "230000200104243285",
    status: false,
    name: "道易军现部",
    code: "YP547",
    manager: "方艳",
    employeeCount: 127,
    description:
      "重你叫度二消并整能属成在如形没。转之十速油市分政指热西真区号系本他者。用样始具当算将传特口准压更运研这半。",
    phone: "16377976259",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "120000201111169377",
        name: "易社工部",
        code: "SKI757",
        manager: "吕丽",
        employeeCount: 18,
        description: "型化江保加近任省已白会华五。",
        children: [
          {
            id: "350000201005282475",
            name: "院时并组",
            code: "FOYT721",
            manager: "程涛",
            employeeCount: 13,
            description: "证还连斯些半身些感查象院引说机取林。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 0,
            __originalIndexPath__: "2.0.0",
            __primaryKey__: "350000201005282475",
          },
          {
            id: "630000201606244279",
            name: "队际记组",
            code: "YK626",
            manager: "卢秀英",
            employeeCount: 8,
            description:
              "通分调领领成还京型识北素电问观做或示。但式第时飞想打道但组酸子期无可听验。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 1,
            __originalIndexPath__: "2.0.1",
            __primaryKey__: "630000201606244279",
          },
          {
            id: "370000199211216608",
            name: "上史斗组",
            code: "RKL033",
            manager: "宋霞",
            employeeCount: 7,
            description:
              "空求电气单并由段目么加史。时上求在务商实于等且列表收行按。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 2,
            __originalIndexPath__: "2.0.2",
            __primaryKey__: "370000199211216608",
          },
        ],
        createdAt: "2024-09-26",
        __originalIndex__: 0,
        __originalIndexPath__: "2.0",
        __primaryKey__: "120000201111169377",
      },
      {
        id: "350000198112185297",
        name: "水些率部",
        code: "DTG846",
        manager: "于洋",
        employeeCount: 48,
        description:
          "己米领京话确义产发速多头交器表置世。化成从其状治千除叫器会常体段期。合存细为非总消务铁有天连等直。",
        children: [
          {
            id: "410000202001258276",
            name: "飞工办组",
            code: "OSL517",
            manager: "孟娜",
            employeeCount: 8,
            description:
              "片高界需道数提况入深区示各则阶热。王金见行百光象须酸不研具意存加。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 0,
            __originalIndexPath__: "2.1.0",
            __primaryKey__: "410000202001258276",
          },
          {
            id: "820000201111182817",
            name: "细情组",
            code: "KCS387",
            manager: "秦明",
            employeeCount: 13,
            description: "任经易连况品活西重该角如克十斗。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 1,
            __originalIndexPath__: "2.1.1",
            __primaryKey__: "820000201111182817",
          },
        ],
        createdAt: "2024-09-27",
        __originalIndex__: 1,
        __originalIndexPath__: "2.1",
        __primaryKey__: "350000198112185297",
      },
      {
        id: "610000200208229614",
        name: "识空在部",
        code: "MJ959",
        manager: "郝艳",
        employeeCount: 34,
        description:
          "采油西关提须专务可民者史习车报部青。选现存边识决织转好年提立市风。",
        children: [
          {
            id: "510000200305115076",
            name: "育经组",
            code: "IFH282",
            manager: "叶丽",
            employeeCount: 12,
            description: "层风影部信事率达南团最求。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 0,
            __originalIndexPath__: "2.2.0",
            __primaryKey__: "510000200305115076",
          },
          {
            id: "520000201811111357",
            name: "从又和组",
            code: "KHD194",
            manager: "贾杰",
            employeeCount: 14,
            description:
              "北做运什起式边却常维工即。现商直再车标造任五运真月全养。",
            children: [],
            createdAt: "2024-09-30",
            __originalIndex__: 1,
            __originalIndexPath__: "2.2.1",
            __primaryKey__: "520000201811111357",
          },
          {
            id: "230000197903310558",
            name: "严书管快组",
            code: "YLB147",
            manager: "何芳",
            employeeCount: 11,
            description:
              "且边革形做难信些山社报段题论利。候照实事据会结美行物公则将还行在白。象求众各等斗机式支习术结证。",
            children: [],
            createdAt: "2024-10-01",
            __originalIndex__: 2,
            __originalIndexPath__: "2.2.2",
            __primaryKey__: "230000197903310558",
          },
        ],
        createdAt: "2024-09-28",
        __originalIndex__: 2,
        __originalIndexPath__: "2.2",
        __primaryKey__: "610000200208229614",
      },
    ],
    createdAt: "2024-09-25 00:00",
  },
  {
    __originalIndex__: 3,
    __primaryKey__: "360000200907124166",
    id: "360000200907124166",
    status: false,
    name: "温气几形部",
    code: "XTQG297",
    manager: "贺敏",
    employeeCount: 106,
    description:
      "多十好热持出每然型府江到按说空义还无。无收构然多你好着样变者叫构展持。",
    phone: "16780741559",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "370000199610124137",
        name: "角存家反部",
        code: "QGE522",
        manager: "陈明",
        employeeCount: 38,
        description: "制革活会适平世个能然列导许二林验回。",
        children: [
          {
            id: "460000197404081597",
            name: "接花出组",
            code: "FU669",
            manager: "任伟",
            employeeCount: 8,
            description:
              "层被明据路万直东大称白然等。性去件角果些年队传照水比样至种油。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 0,
            __originalIndexPath__: "3.0.0",
            __primaryKey__: "460000197404081597",
          },
          {
            id: "430000200612023681",
            name: "权治组",
            code: "KVYE827",
            manager: "曹秀兰",
            employeeCount: 15,
            description:
              "安上要论去都科识始者完何热器老。支量三长它千目被队理十带响则。实认用人手方政商素书传开员。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 1,
            __originalIndexPath__: "3.0.1",
            __primaryKey__: "430000200612023681",
          },
        ],
        createdAt: "2024-09-27",
        __originalIndex__: 0,
        __originalIndexPath__: "3.0",
        __primaryKey__: "370000199610124137",
      },
      {
        id: "350000201612231768",
        name: "知起低引部",
        code: "SUU315",
        manager: "周芳",
        employeeCount: 13,
        description: "月总分主合见验物代上情员济加分将严器。",
        children: [
          {
            id: "440000199108162152",
            name: "般与组",
            code: "ZEI877",
            manager: "谢军",
            employeeCount: 10,
            description: "果参条流完整率文称音科参去称。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 0,
            __originalIndexPath__: "3.1.0",
            __primaryKey__: "440000199108162152",
          },
          {
            id: "820000201910191533",
            name: "准式通组",
            code: "TPL734",
            manager: "杜娜",
            employeeCount: 6,
            description:
              "基界根回度规支矿变需设温。候万点运片维极群山传她建广细声王。",
            children: [],
            createdAt: "2024-09-30",
            __originalIndex__: 1,
            __originalIndexPath__: "3.1.1",
            __primaryKey__: "820000201910191533",
          },
          {
            id: "500000201308196572",
            name: "政口家可组",
            code: "WRNH622",
            manager: "高秀英",
            employeeCount: 9,
            description:
              "物前万直厂问边平利路确王起产革。当界并安劳育个系路作些入对。",
            children: [],
            createdAt: "2024-10-01",
            __originalIndex__: 2,
            __originalIndexPath__: "3.1.2",
            __primaryKey__: "500000201308196572",
          },
        ],
        createdAt: "2024-09-28",
        __originalIndex__: 1,
        __originalIndexPath__: "3.1",
        __primaryKey__: "350000201612231768",
      },
      {
        id: "520000201803169110",
        name: "面流程四部",
        code: "HEWM625",
        manager: "贺刚",
        employeeCount: 36,
        description:
          "率林中等战形见业再关质基习料。地县复道重程七再收育节党名声由价。",
        children: [
          {
            id: "220000201202248496",
            name: "精斯该组",
            code: "QTET847",
            manager: "邱霞",
            employeeCount: 9,
            description:
              "不新历明经可压行候应对必知展与。是也化利作本过能性做备积可低取照。",
            children: [],
            createdAt: "2024-09-30",
            __originalIndex__: 0,
            __originalIndexPath__: "3.2.0",
            __primaryKey__: "220000201202248496",
          },
        ],
        createdAt: "2024-09-29",
        __originalIndex__: 2,
        __originalIndexPath__: "3.2",
        __primaryKey__: "520000201803169110",
      },
    ],
    createdAt: "2024-09-26 00:00",
  },
  {
    __originalIndex__: 4,
    __primaryKey__: "23000019800818641X",
    id: "23000019800818641X",
    status: false,
    name: "根改亲转部",
    code: "VQCC253",
    manager: "魏芳",
    employeeCount: 95,
    description:
      "置前半治强电代可会月就住出因能商真表。之立况名出教根报先温东生型生素商把王。",
    phone: "15511772314",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "320000201310144516",
        name: "明自组将样部",
        code: "YCT617",
        manager: "郑洋",
        employeeCount: 29,
        description:
          "团得分往合科各使你同已九到问按但。矿米战生历行省消众容山东般出战。小有当建者元个北形员听世后适交马前。",
        children: [
          {
            id: "71000019850402502X",
            name: "手低温组",
            code: "TEY203",
            manager: "易静",
            employeeCount: 7,
            description:
              "题体规就能可切化安题己般南问道。龙斯际圆题运品队见后思证具广。现期组要中设受每他次知用常学段强证。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 0,
            __originalIndexPath__: "4.0.0",
            __primaryKey__: "71000019850402502X",
          },
          {
            id: "450000200308203681",
            name: "照式验组",
            code: "OEC126",
            manager: "龙涛",
            employeeCount: 5,
            description: "织确料使也关量根干名己会口维然市思。",
            children: [],
            createdAt: "2024-09-30",
            __originalIndex__: 1,
            __originalIndexPath__: "4.0.1",
            __primaryKey__: "450000200308203681",
          },
        ],
        createdAt: "2024-09-28",
        __originalIndex__: 0,
        __originalIndexPath__: "4.0",
        __primaryKey__: "320000201310144516",
      },
      {
        id: "450000197705168176",
        name: "济面党部",
        code: "NF944",
        manager: "傅芳",
        employeeCount: 41,
        description: "级心等件于则界后好且包次。石但这次下表原说调院带论才。",
        children: [
          {
            id: "530000200502124282",
            name: "又适响组",
            code: "CC743",
            manager: "周芳",
            employeeCount: 7,
            description:
              "热技口八全结整看取该展便易。即报低现物则式需不力验点角。",
            children: [],
            createdAt: "2024-09-30",
            __originalIndex__: 0,
            __originalIndexPath__: "4.1.0",
            __primaryKey__: "530000200502124282",
          },
          {
            id: "440000199306161396",
            name: "与比住组",
            code: "HH078",
            manager: "赵桂英",
            employeeCount: 6,
            description: "在方红亲次铁至点在切性设商派斯克铁石。",
            children: [],
            createdAt: "2024-10-01",
            __originalIndex__: 1,
            __originalIndexPath__: "4.1.1",
            __primaryKey__: "440000199306161396",
          },
          {
            id: "82000019951127311X",
            name: "江至把门组",
            code: "KC324",
            manager: "董明",
            employeeCount: 14,
            description:
              "自质学及车感合集酸石红社律。效识市九次半可选矿建率己阶。",
            children: [],
            createdAt: "2024-10-02",
            __originalIndex__: 2,
            __originalIndexPath__: "4.1.2",
            __primaryKey__: "82000019951127311X",
          },
        ],
        createdAt: "2024-09-29",
        __originalIndex__: 1,
        __originalIndexPath__: "4.1",
        __primaryKey__: "450000197705168176",
      },
      {
        id: "370000199607093157",
        name: "采却达存部",
        code: "ADIL603",
        manager: "魏秀兰",
        employeeCount: 47,
        description: "上信制革阶应铁根书你起律强结。",
        children: [
          {
            id: "120000198401099536",
            name: "影近能组",
            code: "BNT816",
            manager: "叶明",
            employeeCount: 13,
            description:
              "华形段光步直同整世别处完周保科界。与根便干造点教当般指感头院此。",
            children: [],
            createdAt: "2024-10-01",
            __originalIndex__: 0,
            __originalIndexPath__: "4.2.0",
            __primaryKey__: "120000198401099536",
          },
          {
            id: "430000198508299098",
            name: "战与京行组",
            code: "TF375",
            manager: "孟敏",
            employeeCount: 12,
            description: "己采火向导油国计号与展史称总内式常东。",
            children: [],
            createdAt: "2024-10-02",
            __originalIndex__: 1,
            __originalIndexPath__: "4.2.1",
            __primaryKey__: "430000198508299098",
          },
        ],
        createdAt: "2024-09-30",
        __originalIndex__: 2,
        __originalIndexPath__: "4.2",
        __primaryKey__: "370000199607093157",
      },
    ],
    createdAt: "2024-09-27 00:00",
  },
  {
    __originalIndex__: 5,
    __primaryKey__: "120000198510024218",
    id: "120000198510024218",
    status: false,
    name: "而治管部",
    code: "KWR453",
    manager: "黄敏",
    employeeCount: 149,
    description:
      "华又感共代毛东反打书往变研。复红火采变龙斗成美年么三层成变走步。格直国品酸学安劳置出结也这行了。",
    phone: "18330475273",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "41000019720814618X",
        name: "好何中意外部",
        code: "QH424",
        manager: "曾涛",
        employeeCount: 45,
        description:
          "现关原红至数力界山究然明。器二识高战则无层格争老一只联生文由劳。青温速象此直条手究运白地二声连族位。",
        children: [
          {
            id: "210000202106212322",
            name: "般两见组",
            code: "II663",
            manager: "高超",
            employeeCount: 8,
            description:
              "深或新或合任图重性象么府子。干老活至工备化圆除转位政际资革公万名。",
            children: [],
            createdAt: "2024-09-30",
            __originalIndex__: 0,
            __originalIndexPath__: "5.0.0",
            __primaryKey__: "210000202106212322",
          },
          {
            id: "120000200612251438",
            name: "速新相速组",
            code: "UMIH842",
            manager: "陆敏",
            employeeCount: 14,
            description:
              "之真书由温支情那情对什它前农才。自团状系们新难等算按质光参队期。",
            children: [],
            createdAt: "2024-10-01",
            __originalIndex__: 1,
            __originalIndexPath__: "5.0.1",
            __primaryKey__: "120000200612251438",
          },
        ],
        createdAt: "2024-09-29",
        __originalIndex__: 0,
        __originalIndexPath__: "5.0",
        __primaryKey__: "41000019720814618X",
      },
      {
        id: "370000201505319805",
        name: "矿等水克部",
        code: "IV045",
        manager: "范超",
        employeeCount: 23,
        description:
          "阶列理更素大半和反只动现万。影因历山众四研也前电风表近车利结会。消而无局之类各即只东市必利处。",
        children: [
          {
            id: "330000199805190727",
            name: "程算确组",
            code: "JG663",
            manager: "黄超",
            employeeCount: 8,
            description:
              "也计接比易时活边几家无文。史进十前联层率分活院花理回作构管度。",
            children: [],
            createdAt: "2024-10-01",
            __originalIndex__: 0,
            __originalIndexPath__: "5.1.0",
            __primaryKey__: "330000199805190727",
          },
          {
            id: "420000199309305881",
            name: "商族火组",
            code: "XLVG718",
            manager: "邹洋",
            employeeCount: 7,
            description:
              "北物少现认眼没系内工分如。际圆又离极例才际量花统向最车各格才之。",
            children: [],
            createdAt: "2024-10-02",
            __originalIndex__: 1,
            __originalIndexPath__: "5.1.1",
            __primaryKey__: "420000199309305881",
          },
          {
            id: "54000019711212783X",
            name: "状因组",
            code: "HI036",
            manager: "邓强",
            employeeCount: 8,
            description:
              "历思回老日众身党局五只支门真并专风于。可素如社义较制需期者国会出又起精亲。",
            children: [],
            createdAt: "2024-10-03",
            __originalIndex__: 2,
            __originalIndexPath__: "5.1.2",
            __primaryKey__: "54000019711212783X",
          },
        ],
        createdAt: "2024-09-30",
        __originalIndex__: 1,
        __originalIndexPath__: "5.1",
        __primaryKey__: "370000201505319805",
      },
      {
        id: "340000197503284851",
        name: "金斯易好却部",
        code: "NRRU524",
        manager: "邱磊",
        employeeCount: 35,
        description:
          "次他细几发变权对式内到水车速么。教状只来改厂压科往单老什音号界率。",
        children: [
          {
            id: "440000198006213030",
            name: "记元体导组",
            code: "VWF647",
            manager: "林娟",
            employeeCount: 14,
            description:
              "收支美路出党影下五山济水便任用。处布料统声话装很格质学同究声。",
            children: [],
            createdAt: "2024-10-02",
            __originalIndex__: 0,
            __originalIndexPath__: "5.2.0",
            __primaryKey__: "440000198006213030",
          },
        ],
        createdAt: "2024-10-01",
        __originalIndex__: 2,
        __originalIndexPath__: "5.2",
        __primaryKey__: "340000197503284851",
      },
    ],
    createdAt: "2024-09-28 00:00",
  },
  {
    __originalIndex__: 6,
    __primaryKey__: "220000199905249049",
    id: "220000199905249049",
    status: true,
    name: "到气于影部",
    code: "GRK984",
    manager: "易涛",
    employeeCount: 155,
    description:
      "其率术商七学置采当样个改打算给。及林速历传二包发研气国林生须前按。次存也性色达理身认事活快周元国。",
    phone: "18564822598",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "640000202002214294",
        name: "所属世方东部",
        code: "HOI238",
        manager: "赖明",
        employeeCount: 45,
        description:
          "存相六大实火革龙切光什委其基。地单照说前产史色群林查太过活千压效根。",
        children: [
          {
            id: "130000200810264389",
            name: "较历高才组",
            code: "BJ202",
            manager: "尹刚",
            employeeCount: 15,
            description: "同反军受的得能飞何管利为动维按表调度。",
            children: [],
            createdAt: "2024-10-01",
            __originalIndex__: 0,
            __originalIndexPath__: "6.0.0",
            __primaryKey__: "130000200810264389",
          },
          {
            id: "620000197710255735",
            name: "化资志组",
            code: "GKY476",
            manager: "蒋平",
            employeeCount: 12,
            description:
              "解同度农更油连级革么结术养准。大起我活传快合教快级建条常接即。",
            children: [],
            createdAt: "2024-10-02",
            __originalIndex__: 1,
            __originalIndexPath__: "6.0.1",
            __primaryKey__: "620000197710255735",
          },
        ],
        createdAt: "2024-09-30",
        __originalIndex__: 0,
        __originalIndexPath__: "6.0",
        __primaryKey__: "640000202002214294",
      },
      {
        id: "140000198305065276",
        name: "也往信它部",
        code: "MSG578",
        manager: "于芳",
        employeeCount: 12,
        description: "天感速气积形级级装法选处。",
        children: [
          {
            id: "340000197110231425",
            name: "影通青算组",
            code: "KVO546",
            manager: "赖洋",
            employeeCount: 11,
            description:
              "算多林果数团共位声半整无识究先重其历。同他更回别事果到因每是改着象主。子部土体群面表部你今见具该。",
            children: [],
            createdAt: "2024-10-02",
            __originalIndex__: 0,
            __originalIndexPath__: "6.1.0",
            __primaryKey__: "340000197110231425",
          },
          {
            id: "210000200903103306",
            name: "们道转组",
            code: "OVH678",
            manager: "高娜",
            employeeCount: 8,
            description:
              "程意任国华必观头种如声那叫力色九。质话物通看族问没规开院音金且率重类大。",
            children: [],
            createdAt: "2024-10-03",
            __originalIndex__: 1,
            __originalIndexPath__: "6.1.1",
            __primaryKey__: "210000200903103306",
          },
          {
            id: "530000201607031183",
            name: "想国组",
            code: "MK384",
            manager: "侯伟",
            employeeCount: 5,
            description:
              "可不增具青会些子养群证业之标认展直调。的多类响说学片长张农治调。战根火说应路三山究革变取派山金决。",
            children: [],
            createdAt: "2024-10-04",
            __originalIndex__: 2,
            __originalIndexPath__: "6.1.2",
            __primaryKey__: "530000201607031183",
          },
        ],
        createdAt: "2024-10-01",
        __originalIndex__: 1,
        __originalIndexPath__: "6.1",
        __primaryKey__: "140000198305065276",
      },
      {
        id: "350000201701039719",
        name: "再常支争部",
        code: "NP034",
        manager: "武敏",
        employeeCount: 28,
        description:
          "越七部报常现音张电养基至每。局收去规格应消办到光确易几即和体存图。",
        children: [
          {
            id: "350000201301113801",
            name: "省往员组",
            code: "MMSI544",
            manager: "顾娜",
            employeeCount: 13,
            description:
              "能影半易料近际设权品查如那。政么情节无质基增议易从技八写。",
            children: [],
            createdAt: "2024-10-03",
            __originalIndex__: 0,
            __originalIndexPath__: "6.2.0",
            __primaryKey__: "350000201301113801",
          },
          {
            id: "500000200709179453",
            name: "民南型族组",
            code: "IWU501",
            manager: "廖刚",
            employeeCount: 14,
            description: "区转价日速什格期计化无声。",
            children: [],
            createdAt: "2024-10-04",
            __originalIndex__: 1,
            __originalIndexPath__: "6.2.1",
            __primaryKey__: "500000200709179453",
          },
          {
            id: "210000197908309771",
            name: "没布年组",
            code: "QLG523",
            manager: "江娟",
            employeeCount: 7,
            description:
              "说金江六省历交极风干使然边先然。包意后写民月体知确回感亲划听清。气历金细些正正正想关特身技海体一。",
            children: [],
            createdAt: "2024-10-05",
            __originalIndex__: 2,
            __originalIndexPath__: "6.2.2",
            __primaryKey__: "210000197908309771",
          },
        ],
        createdAt: "2024-10-02",
        __originalIndex__: 2,
        __originalIndexPath__: "6.2",
        __primaryKey__: "350000201701039719",
      },
    ],
    createdAt: "2024-09-29 00:00",
  },
  {
    __originalIndex__: 7,
    __primaryKey__: "430000201506018744",
    id: "430000201506018744",
    status: false,
    name: "提九分亲部",
    code: "MRX424",
    manager: "贺军",
    employeeCount: 200,
    description:
      "标北近几织传应党产保取计那七只。就十准情接音话义石易万斗团。量少交标产状结提斗行响解素引千般来平。",
    phone: "15616341132",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "530000200809301247",
        name: "史千重号养部",
        code: "JG399",
        manager: "余秀英",
        employeeCount: 14,
        description: "科压处则作者人持区品华战段阶。过然结义走持电后地计农劳。",
        children: [
          {
            id: "430000197511265521",
            name: "然公经组",
            code: "DLWK312",
            manager: "赵秀英",
            employeeCount: 9,
            description:
              "达达感这验克习较克何通采东风。准压类元日记到空利用级育别低一。",
            children: [],
            createdAt: "2024-09-25",
            __originalIndex__: 0,
            __originalIndexPath__: "7.0.0",
            __primaryKey__: "430000197511265521",
          },
        ],
        createdAt: "2024-09-24",
        __originalIndex__: 0,
        __originalIndexPath__: "7.0",
        __primaryKey__: "530000200809301247",
      },
      {
        id: "630000201006104299",
        name: "议说万部",
        code: "IPN475",
        manager: "廖强",
        employeeCount: 23,
        description: "给象场正物史关解转矿务入命。",
        children: [
          {
            id: "320000198306211988",
            name: "器属叫组",
            code: "DE672",
            manager: "宋娟",
            employeeCount: 13,
            description:
              "习非段立你容道从办劳得林。角对南战越心期数织次最能行该花计之。",
            children: [],
            createdAt: "2024-09-26",
            __originalIndex__: 0,
            __originalIndexPath__: "7.1.0",
            __primaryKey__: "320000198306211988",
          },
          {
            id: "650000197405204638",
            name: "先次组",
            code: "SS812",
            manager: "谭勇",
            employeeCount: 7,
            description:
              "示圆受发立型口工计天选术命西千局。大我约书成积部况劳需精毛而九收。速类斯建规自领果去参土厂史一那争意日。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 1,
            __originalIndexPath__: "7.1.1",
            __primaryKey__: "650000197405204638",
          },
        ],
        createdAt: "2024-09-25",
        __originalIndex__: 1,
        __originalIndexPath__: "7.1",
        __primaryKey__: "630000201006104299",
      },
      {
        id: "210000198004159170",
        name: "江过县部",
        code: "SUI584",
        manager: "周娟",
        employeeCount: 35,
        description:
          "车表部号月子律军斯内划必地被而严听也。话传强体资候一铁又过况引方。取应铁身在己算示达属眼人万门般。",
        children: [
          {
            id: "510000201204147807",
            name: "之节度组",
            code: "USU272",
            manager: "蔡霞",
            employeeCount: 7,
            description:
              "专么入酸支增义区须团据边构已石有。信住业只能计九它管以准两机商四知先以。速部类资力信风参三当快看。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 0,
            __originalIndexPath__: "7.2.0",
            __primaryKey__: "510000201204147807",
          },
          {
            id: "620000197312313434",
            name: "回装组",
            code: "GGV068",
            manager: "谭磊",
            employeeCount: 12,
            description:
              "小究是成义效行色都细目响意即济复性。般别少知毛类切米习要识次制。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 1,
            __originalIndexPath__: "7.2.1",
            __primaryKey__: "620000197312313434",
          },
        ],
        createdAt: "2024-09-26",
        __originalIndex__: 2,
        __originalIndexPath__: "7.2",
        __primaryKey__: "210000198004159170",
      },
      {
        id: "990000201505042581",
        name: "公较约派部",
        code: "IGWH711",
        manager: "邵洋",
        employeeCount: 27,
        description: "标战离增基动识六义族实究众来。",
        children: [
          {
            id: "620000202309133540",
            name: "代领行已组",
            code: "QEHY332",
            manager: "范娟",
            employeeCount: 9,
            description:
              "级点造县多前队金青亲三只备。近化备按论干十到保六何象说。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 0,
            __originalIndexPath__: "7.3.0",
            __primaryKey__: "620000202309133540",
          },
          {
            id: "41000020011209368X",
            name: "今月族她组",
            code: "ISL714",
            manager: "叶超",
            employeeCount: 9,
            description:
              "高了决按示流这织引素研三。电满元南即除党指能才边看元展许。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 1,
            __originalIndexPath__: "7.3.1",
            __primaryKey__: "41000020011209368X",
          },
        ],
        createdAt: "2024-09-27",
        __originalIndex__: 3,
        __originalIndexPath__: "7.3",
        __primaryKey__: "990000201505042581",
      },
    ],
    createdAt: "2024-09-23 00:00",
  },
  {
    __originalIndex__: 8,
    __primaryKey__: "360000199209198680",
    id: "360000199209198680",
    status: false,
    name: "东前难始引部",
    code: "SUZU343",
    manager: "李秀兰",
    employeeCount: 133,
    description:
      "为林理设理书验金人高论到量。求战意数及商算什复而级断而清一需。",
    phone: "17459196526",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "330000200409022479",
        name: "选见华周部",
        code: "YQVY321",
        manager: "叶霞",
        employeeCount: 31,
        description: "金才增联者完后参段证但把。",
        children: [
          {
            id: "500000201902171052",
            name: "按领话组",
            code: "YGV579",
            manager: "龚伟",
            employeeCount: 7,
            description:
              "技去今生观单入重只二员派我器示。克花车比法族适交响意将资统全别通。半类口节市号叫效于青条常金。",
            children: [],
            createdAt: "2024-09-26",
            __originalIndex__: 0,
            __originalIndexPath__: "8.0.0",
            __primaryKey__: "500000201902171052",
          },
          {
            id: "820000201908032779",
            name: "易难口外组",
            code: "QXFE443",
            manager: "曾秀英",
            employeeCount: 9,
            description:
              "很影离量切保几格光在查场将划经。三群快办且断造样常空完称往。长对只南她声非海个学新较持名只基。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 1,
            __originalIndexPath__: "8.0.1",
            __primaryKey__: "820000201908032779",
          },
        ],
        createdAt: "2024-09-25",
        __originalIndex__: 0,
        __originalIndexPath__: "8.0",
        __primaryKey__: "330000200409022479",
      },
      {
        id: "810000199303061962",
        name: "间和铁广再部",
        code: "HKK887",
        manager: "程磊",
        employeeCount: 35,
        description: "历起引统明易地县度土物心眼世清解。",
        children: [
          {
            id: "140000199701054629",
            name: "战院组",
            code: "LAE429",
            manager: "余娟",
            employeeCount: 15,
            description:
              "气工个权放酸因圆且群市先写别情。日度长形力除分眼光京见铁在志感程。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 0,
            __originalIndexPath__: "8.1.0",
            __primaryKey__: "140000199701054629",
          },
          {
            id: "450000200312167564",
            name: "八教议江组",
            code: "UFN606",
            manager: "毛涛",
            employeeCount: 7,
            description: "观先学之进海还响将众步门场传群般许。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 1,
            __originalIndexPath__: "8.1.1",
            __primaryKey__: "450000200312167564",
          },
        ],
        createdAt: "2024-09-26",
        __originalIndex__: 1,
        __originalIndexPath__: "8.1",
        __primaryKey__: "810000199303061962",
      },
    ],
    createdAt: "2024-09-24 00:00",
  },
  {
    __originalIndex__: 9,
    __primaryKey__: "230000201211107128",
    id: "230000201211107128",
    status: true,
    name: "市铁按传部",
    code: "NOOY811",
    manager: "周明",
    employeeCount: 89,
    description:
      "细以上算如议般热都教题合设级统价叫。阶局的始叫信长主位学收准识为农万一命。",
    phone: "17338243932",
    img: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    children: [
      {
        id: "430000200704244166",
        name: "代设观部",
        code: "EDO861",
        manager: "段明",
        employeeCount: 45,
        description:
          "习约且商支自些张太快基正立技。众证每号信好达布义入毛题越达色们。",
        children: [
          {
            id: "130000199311167626",
            name: "期院民组",
            code: "WUO217",
            manager: "谢敏",
            employeeCount: 12,
            description: "度好个干方起受斯路划须群农。",
            children: [],
            createdAt: "2024-09-27",
            __originalIndex__: 0,
            __originalIndexPath__: "9.0.0",
            __primaryKey__: "130000199311167626",
          },
          {
            id: "350000197806084410",
            name: "百我约志组",
            code: "CTBK364",
            manager: "陆军",
            employeeCount: 5,
            description: "五展花何信动化真断准现事节数。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 1,
            __originalIndexPath__: "9.0.1",
            __primaryKey__: "350000197806084410",
          },
        ],
        createdAt: "2024-09-26",
        __originalIndex__: 0,
        __originalIndexPath__: "9.0",
        __primaryKey__: "430000200704244166",
      },
      {
        id: "340000197210285471",
        name: "之专率部",
        code: "KPK216",
        manager: "曹超",
        employeeCount: 13,
        description: "拉明适为特系转压管果省话南历。",
        children: [
          {
            id: "440000200807223618",
            name: "为完组",
            code: "WYP739",
            manager: "侯娟",
            employeeCount: 9,
            description: "节次约维相圆好多米书现很类备。",
            children: [],
            createdAt: "2024-09-28",
            __originalIndex__: 0,
            __originalIndexPath__: "9.1.0",
            __primaryKey__: "440000200807223618",
          },
          {
            id: "530000197809154828",
            name: "条自却组",
            code: "DFT541",
            manager: "董秀兰",
            employeeCount: 9,
            description:
              "层但需总光展构区口节便多包料的选看号。地市很政型并声命查前角几温报细。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 1,
            __originalIndexPath__: "9.1.1",
            __primaryKey__: "530000197809154828",
          },
        ],
        createdAt: "2024-09-27",
        __originalIndex__: 1,
        __originalIndexPath__: "9.1",
        __primaryKey__: "340000197210285471",
      },
      {
        id: "820000198106220773",
        name: "物最八部",
        code: "RGP215",
        manager: "丁霞",
        employeeCount: 13,
        description:
          "造安共族然所满县强织解省酸何进机。意住原积老金高月点风并传二不装。",
        children: [
          {
            id: "440000199712112987",
            name: "儿真组",
            code: "RDYD183",
            manager: "崔静",
            employeeCount: 14,
            description: "以正九研感办整共口整几认声法教听局老。",
            children: [],
            createdAt: "2024-09-29",
            __originalIndex__: 0,
            __originalIndexPath__: "9.2.0",
            __primaryKey__: "440000199712112987",
          },
          {
            id: "220000198301051854",
            name: "米前组",
            code: "QS166",
            manager: "邓涛",
            employeeCount: 14,
            description:
              "就王把界它示火高候政适治公千位。路反位加度料选速决研新家。",
            children: [],
            createdAt: "2024-09-30",
            __originalIndex__: 1,
            __originalIndexPath__: "9.2.1",
            __primaryKey__: "220000198301051854",
          },
        ],
        createdAt: "2024-09-28",
        __originalIndex__: 2,
        __originalIndexPath__: "9.2",
        __primaryKey__: "820000198106220773",
      },
    ],
    createdAt: "2024-09-25 00:00",
  },
];
export const columns = [
  {
    id: "id",
    Header: "id",
    alias: "id",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "input",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 0,
      width: 150,
      originalId: "id",
      id: "id",
      alias: "id",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "id",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "630000199501101896",
        "430000201311103869",
        "230000200104243285",
        "360000200907124166",
        "23000019800818641X",
        "120000198510024218",
        "220000199905249049",
        "430000201506018744",
        "360000199209198680",
        "230000201211107128",
      ],
      computedValue: [
        "630000199501101896",
        "430000201311103869",
        "230000200104243285",
        "360000200907124166",
        "23000019800818641X",
        "120000198510024218",
        "220000199905249049",
        "430000201506018744",
        "360000199209198680",
        "230000201211107128",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "id",
    dataIndex: "id",
    ellipsis: true,
    valueType: "input",
    formItemProps: {
      rules: [
        {
          type: "string",
          message: "id的长度必须在0到+∞之间",
        },
      ],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 0,
      width: 150,
      originalId: "id",
      id: "id",
      alias: "id",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "id",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "630000199501101896",
        "430000201311103869",
        "230000200104243285",
        "360000200907124166",
        "23000019800818641X",
        "120000198510024218",
        "220000199905249049",
        "430000201506018744",
        "360000199209198680",
        "230000201211107128",
      ],
      computedValue: [
        "630000199501101896",
        "430000201311103869",
        "230000200104243285",
        "360000200907124166",
        "23000019800818641X",
        "120000198510024218",
        "220000199905249049",
        "430000201506018744",
        "360000199209198680",
        "230000201211107128",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "status",
    Header: "status",
    alias: "status",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "switch",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 1,
      width: 150,
      originalId: "status",
      id: "status",
      alias: "status",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "switch",
      textSize: "0.875rem",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "status",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      computedValue: [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "status",
    dataIndex: "status",
    ellipsis: true,
    valueType: "switch",
    formItemProps: {
      rules: [],
    },
    valueEnum: {
      false: {
        text: "false",
        label: "false",
        value: false,
      },
      true: {
        text: "true",
        label: "true",
        value: true,
      },
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 1,
      width: 150,
      originalId: "status",
      id: "status",
      alias: "status",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "switch",
      textSize: "0.875rem",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "status",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      computedValue: [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "name",
    Header: "name",
    alias: "name",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "input",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 2,
      width: 150,
      originalId: "name",
      id: "name",
      alias: "name",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "name",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "电群研共国部",
        "军运原条部",
        "道易军现部",
        "温气几形部",
        "根改亲转部",
        "而治管部",
        "到气于影部",
        "提九分亲部",
        "东前难始引部",
        "市铁按传部",
      ],
      computedValue: [
        "电群研共国部",
        "军运原条部",
        "道易军现部",
        "温气几形部",
        "根改亲转部",
        "而治管部",
        "到气于影部",
        "提九分亲部",
        "东前难始引部",
        "市铁按传部",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "name",
    dataIndex: "name",
    ellipsis: true,
    valueType: "input",
    formItemProps: {
      rules: [
        {
          type: "string",
          message: "name的长度必须在0到+∞之间",
        },
      ],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 2,
      width: 150,
      originalId: "name",
      id: "name",
      alias: "name",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "name",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "电群研共国部",
        "军运原条部",
        "道易军现部",
        "温气几形部",
        "根改亲转部",
        "而治管部",
        "到气于影部",
        "提九分亲部",
        "东前难始引部",
        "市铁按传部",
      ],
      computedValue: [
        "电群研共国部",
        "军运原条部",
        "道易军现部",
        "温气几形部",
        "根改亲转部",
        "而治管部",
        "到气于影部",
        "提九分亲部",
        "东前难始引部",
        "市铁按传部",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "code",
    Header: "code",
    alias: "code",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "input",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 3,
      width: 150,
      originalId: "code",
      id: "code",
      alias: "code",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "code",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "GCOB301",
        "XPSV636",
        "YP547",
        "XTQG297",
        "VQCC253",
        "KWR453",
        "GRK984",
        "MRX424",
        "SUZU343",
        "NOOY811",
      ],
      computedValue: [
        "GCOB301",
        "XPSV636",
        "YP547",
        "XTQG297",
        "VQCC253",
        "KWR453",
        "GRK984",
        "MRX424",
        "SUZU343",
        "NOOY811",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "code",
    dataIndex: "code",
    ellipsis: true,
    valueType: "input",
    formItemProps: {
      rules: [
        {
          type: "string",
          message: "code的长度必须在0到+∞之间",
        },
      ],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 3,
      width: 150,
      originalId: "code",
      id: "code",
      alias: "code",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "code",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "GCOB301",
        "XPSV636",
        "YP547",
        "XTQG297",
        "VQCC253",
        "KWR453",
        "GRK984",
        "MRX424",
        "SUZU343",
        "NOOY811",
      ],
      computedValue: [
        "GCOB301",
        "XPSV636",
        "YP547",
        "XTQG297",
        "VQCC253",
        "KWR453",
        "GRK984",
        "MRX424",
        "SUZU343",
        "NOOY811",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "manager",
    Header: "manager",
    alias: "manager",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "input",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 4,
      width: 150,
      originalId: "manager",
      id: "manager",
      alias: "manager",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "manager",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "梁超",
        "郑芳",
        "方艳",
        "贺敏",
        "魏芳",
        "黄敏",
        "易涛",
        "贺军",
        "李秀兰",
        "周明",
      ],
      computedValue: [
        "梁超",
        "郑芳",
        "方艳",
        "贺敏",
        "魏芳",
        "黄敏",
        "易涛",
        "贺军",
        "李秀兰",
        "周明",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "manager",
    dataIndex: "manager",
    ellipsis: true,
    valueType: "input",
    formItemProps: {
      rules: [
        {
          type: "string",
          message: "manager的长度必须在0到+∞之间",
        },
      ],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 4,
      width: 150,
      originalId: "manager",
      id: "manager",
      alias: "manager",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "manager",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "梁超",
        "郑芳",
        "方艳",
        "贺敏",
        "魏芳",
        "黄敏",
        "易涛",
        "贺军",
        "李秀兰",
        "周明",
      ],
      computedValue: [
        "梁超",
        "郑芳",
        "方艳",
        "贺敏",
        "魏芳",
        "黄敏",
        "易涛",
        "贺军",
        "李秀兰",
        "周明",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "employeeCount",
    Header: "employeeCount",
    alias: "employeeCount",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "digit",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 5,
      width: 150,
      originalId: "employeeCount",
      id: "employeeCount",
      alias: "employeeCount",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "digit",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "employeeCount",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [116, 53, 127, 106, 95, 149, 155, 200, 133, 89],
      computedValue: [116, 53, 127, 106, 95, 149, 155, 200, 133, 89],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "employeeCount",
    dataIndex: "employeeCount",
    ellipsis: true,
    valueType: "digit",
    formItemProps: {
      rules: [
        {
          type: "number",
          message: "employeeCount必须在-∞到+∞之间",
        },
      ],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 5,
      width: 150,
      originalId: "employeeCount",
      id: "employeeCount",
      alias: "employeeCount",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "digit",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "employeeCount",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [116, 53, 127, 106, 95, 149, 155, 200, 133, 89],
      computedValue: [116, 53, 127, 106, 95, 149, 155, 200, 133, 89],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "description",
    Header: "description",
    alias: "description",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "input",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 6,
      width: 150,
      originalId: "description",
      id: "description",
      alias: "description",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "description",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "个整油照定家集信风质生率工圆毛华。极听置常联该么积论养确专声生。",
        "条路并重调养用复究速层被。",
        "重你叫度二消并整能属成在如形没。转之十速油市分政指热西真区号系本他者。用样始具当算将传特口准压更运研这半。",
        "多十好热持出每然型府江到按说空义还无。无收构然多你好着样变者叫构展持。",
        "置前半治强电代可会月就住出因能商真表。之立况名出教根报先温东生型生素商把王。",
        "华又感共代毛东反打书往变研。复红火采变龙斗成美年么三层成变走步。格直国品酸学安劳置出结也这行了。",
        "其率术商七学置采当样个改打算给。及林速历传二包发研气国林生须前按。次存也性色达理身认事活快周元国。",
        "标北近几织传应党产保取计那七只。就十准情接音话义石易万斗团。量少交标产状结提斗行响解素引千般来平。",
        "为林理设理书验金人高论到量。求战意数及商算什复而级断而清一需。",
        "细以上算如议般热都教题合设级统价叫。阶局的始叫信长主位学收准识为农万一命。",
      ],
      computedValue: [
        "个整油照定家集信风质生率工圆毛华。极听置常联该么积论养确专声生。",
        "条路并重调养用复究速层被。",
        "重你叫度二消并整能属成在如形没。转之十速油市分政指热西真区号系本他者。用样始具当算将传特口准压更运研这半。",
        "多十好热持出每然型府江到按说空义还无。无收构然多你好着样变者叫构展持。",
        "置前半治强电代可会月就住出因能商真表。之立况名出教根报先温东生型生素商把王。",
        "华又感共代毛东反打书往变研。复红火采变龙斗成美年么三层成变走步。格直国品酸学安劳置出结也这行了。",
        "其率术商七学置采当样个改打算给。及林速历传二包发研气国林生须前按。次存也性色达理身认事活快周元国。",
        "标北近几织传应党产保取计那七只。就十准情接音话义石易万斗团。量少交标产状结提斗行响解素引千般来平。",
        "为林理设理书验金人高论到量。求战意数及商算什复而级断而清一需。",
        "细以上算如议般热都教题合设级统价叫。阶局的始叫信长主位学收准识为农万一命。",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "description",
    dataIndex: "description",
    ellipsis: true,
    valueType: "input",
    formItemProps: {
      rules: [
        {
          type: "string",
          message: "description的长度必须在0到+∞之间",
        },
      ],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 6,
      width: 150,
      originalId: "description",
      id: "description",
      alias: "description",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "description",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "个整油照定家集信风质生率工圆毛华。极听置常联该么积论养确专声生。",
        "条路并重调养用复究速层被。",
        "重你叫度二消并整能属成在如形没。转之十速油市分政指热西真区号系本他者。用样始具当算将传特口准压更运研这半。",
        "多十好热持出每然型府江到按说空义还无。无收构然多你好着样变者叫构展持。",
        "置前半治强电代可会月就住出因能商真表。之立况名出教根报先温东生型生素商把王。",
        "华又感共代毛东反打书往变研。复红火采变龙斗成美年么三层成变走步。格直国品酸学安劳置出结也这行了。",
        "其率术商七学置采当样个改打算给。及林速历传二包发研气国林生须前按。次存也性色达理身认事活快周元国。",
        "标北近几织传应党产保取计那七只。就十准情接音话义石易万斗团。量少交标产状结提斗行响解素引千般来平。",
        "为林理设理书验金人高论到量。求战意数及商算什复而级断而清一需。",
        "细以上算如议般热都教题合设级统价叫。阶局的始叫信长主位学收准识为农万一命。",
      ],
      computedValue: [
        "个整油照定家集信风质生率工圆毛华。极听置常联该么积论养确专声生。",
        "条路并重调养用复究速层被。",
        "重你叫度二消并整能属成在如形没。转之十速油市分政指热西真区号系本他者。用样始具当算将传特口准压更运研这半。",
        "多十好热持出每然型府江到按说空义还无。无收构然多你好着样变者叫构展持。",
        "置前半治强电代可会月就住出因能商真表。之立况名出教根报先温东生型生素商把王。",
        "华又感共代毛东反打书往变研。复红火采变龙斗成美年么三层成变走步。格直国品酸学安劳置出结也这行了。",
        "其率术商七学置采当样个改打算给。及林速历传二包发研气国林生须前按。次存也性色达理身认事活快周元国。",
        "标北近几织传应党产保取计那七只。就十准情接音话义石易万斗团。量少交标产状结提斗行响解素引千般来平。",
        "为林理设理书验金人高论到量。求战意数及商算什复而级断而清一需。",
        "细以上算如议般热都教题合设级统价叫。阶局的始叫信长主位学收准识为农万一命。",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "phone",
    Header: "phone",
    alias: "phone",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "input",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 7,
      width: 150,
      originalId: "phone",
      id: "phone",
      alias: "phone",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "phone",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "19728776313",
        "17322202444",
        "16377976259",
        "16780741559",
        "15511772314",
        "18330475273",
        "18564822598",
        "15616341132",
        "17459196526",
        "17338243932",
      ],
      computedValue: [
        "19728776313",
        "17322202444",
        "16377976259",
        "16780741559",
        "15511772314",
        "18330475273",
        "18564822598",
        "15616341132",
        "17459196526",
        "17338243932",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "phone",
    dataIndex: "phone",
    ellipsis: true,
    valueType: "input",
    formItemProps: {
      rules: [
        {
          type: "string",
          message: "phone的长度必须在0到+∞之间",
        },
      ],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 7,
      width: 150,
      originalId: "phone",
      id: "phone",
      alias: "phone",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "input",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "phone",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "19728776313",
        "17322202444",
        "16377976259",
        "16780741559",
        "15511772314",
        "18330475273",
        "18564822598",
        "15616341132",
        "17459196526",
        "17338243932",
      ],
      computedValue: [
        "19728776313",
        "17322202444",
        "16377976259",
        "16780741559",
        "15511772314",
        "18330475273",
        "18564822598",
        "15616341132",
        "17459196526",
        "17338243932",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "img",
    Header: "img",
    alias: "img",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "image",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 8,
      width: 150,
      originalId: "img",
      id: "img",
      alias: "img",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "image",
      textSize: "0.875rem",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "img",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
      ],
      computedValue: [
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "img",
    dataIndex: "img",
    ellipsis: true,
    valueType: "image",
    formItemProps: {
      rules: [],
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 8,
      width: "100%",
      originalId: "img",
      id: "img",
      alias: "img",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "image",
      textSize: "0.875rem",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "img",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
      ],
      computedValue: [
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
  {
    id: "createdAt",
    Header: "createdAt",
    alias: "createdAt",
    width: 120,
    minWidth: 60,
    draggable: true,
    isHidden: false,
    isDerived: false,
    metaProperties: {
      isHidden: false,
      type: "date",
      format: "YYYY-MM-DD HH:mm",
      inputFormat: "YYYY-MM-DD HH:mm",
    },
    columnProperties: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 10,
      width: 150,
      originalId: "createdAt",
      id: "createdAt",
      alias: "createdAt",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "date",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "createdAt",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
        "2024-09-26",
        "2024-09-27",
        "2024-09-28",
        "2024-09-29",
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
      ],
      computedValue: [
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
        "2024-09-26",
        "2024-09-27",
        "2024-09-28",
        "2024-09-29",
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
    },
    fixed: false,
    hideInTable: false,
    title: "createdAt",
    dataIndex: "createdAt",
    ellipsis: true,
    valueType: "date",
    formItemProps: {
      rules: [],
    },
    valueEnum: {
      "2024-09-23": {
        text: "2024-09-23",
        label: "2024-09-23",
        value: "2024-09-23",
      },
      "2024-09-24": {
        text: "2024-09-24",
        label: "2024-09-24",
        value: "2024-09-24",
      },
      "2024-09-25": {
        text: "2024-09-25",
        label: "2024-09-25",
        value: "2024-09-25",
      },
      "2024-09-26": {
        text: "2024-09-26",
        label: "2024-09-26",
        value: "2024-09-26",
      },
      "2024-09-27": {
        text: "2024-09-27",
        label: "2024-09-27",
        value: "2024-09-27",
      },
      "2024-09-28": {
        text: "2024-09-28",
        label: "2024-09-28",
        value: "2024-09-28",
      },
      "2024-09-29": {
        text: "2024-09-29",
        label: "2024-09-29",
        value: "2024-09-29",
      },
    },
    fieldProps: {
      options: [],
      labelKey: "label",
      valueKey: "value",
      optionsKey: "options",
      childrenKey: "children",
      inputFormat: "YYYY-MM-DD HH:mm",
      outputFormat: "YYYY-MM-DD HH:mm",
      allowCellWrapping: false,
      index: 10,
      width: 150,
      originalId: "createdAt",
      id: "createdAt",
      alias: "createdAt",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      columnType: "date",
      textColor: "",
      textSize: "0.875rem",
      fontStyle: "",
      enableFilter: true,
      enableSort: true,
      isVisible: true,
      isDisabled: false,
      isCellEditable: false,
      isEditable: false,
      isCellVisible: true,
      isVisibleCellFilters: false,
      isCellCopyable: false,
      isVisibleCellSearch: true,
      isDerived: false,
      label: "createdAt",
      isSaveVisible: true,
      isDiscardVisible: true,
      displayText: [
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
        "2024-09-26",
        "2024-09-27",
        "2024-09-28",
        "2024-09-29",
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
      ],
      computedValue: [
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
        "2024-09-26",
        "2024-09-27",
        "2024-09-28",
        "2024-09-29",
        "2024-09-23",
        "2024-09-24",
        "2024-09-25",
      ],
      sticky: "",
      validation: {},
      cellBackground: "",
      fieldNames: {
        label: "label",
        value: "value",
        children: "children",
        key: "value",
        title: "label",
      },
      format: "YYYY-MM-DD HH:mm",
    },
    copyable: false,
    filters: false,
    onFilter: true,
    hideInSearch: false,
  },
];
