import type { ProFormItemProps } from "@ant-design/pro-components";
import type { Alignment } from "@blueprintjs/core";
import type { AntdLabelPosition } from "components/constants";
import type { IconName } from "design-system-old";
import type { WidgetProps } from "widgets/BaseWidget";
import type { InputTypes } from "widgets/BaseInputWidget/constants";
import { NumberInputStepButtonPosition } from "widgets/BaseInputWidget/constants";
import type { SizeType } from "antd/es/config-provider/SizeContext";
export interface AntdInputWidgetProps extends WidgetProps {
  defaultValue?: string | number;
  maxChars?: number;
  isSpellCheck?: boolean;
  maxNum?: number;
  minNum?: number;
  inputText: string;
  inputType: InputTypes;
  tooltip?: string;
  isDisabled?: boolean;
  validation: boolean;
  text: string;
  regex?: string;
  errorMessage?: string;
  placeholderText?: string;
  label: string;
  labelPosition?: AntdLabelPosition;
  labelAlignment?: ProFormItemProps["labelAlign"];
  labelWidth?: number;
  labelTextColor?: string;
  labelTextSize?: string;
  labelStyle?: string;
  isValid: boolean;
  focusIndex?: number;
  isAutoFocusEnabled?: boolean;
  isRequired?: boolean;
  isFocused?: boolean;
  isDirty?: boolean;
  autoFocus?: boolean;
  iconName?: IconName;
  iconAlign?: Omit<Alignment, "center">;
  onSubmit?: string;
  controlSize?: SizeType;
}
